runtime: python39

entrypoint: gunicorn -b :$PORT -w 2 app:app

instance_class: F1

env_variables:
  FLASK_ENV: anime
  SECRET_KEY: 123qwe

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
